# -*- coding: utf-8 -*-
"""
/***************************************************************************
 validateDialog
                                 A QGIS plugin
 Herramienta que analiza la estructura de la direccion
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-12
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Servinformacion
        email                : leonardo.maetinez@servinformacion.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

Module: validaciones_dialog
=============================

This module provides the main dialog interface for the PostgreSQL Permission Management plugin.
It handles user interaction for managing database permissions including:

- Validating database connections
- Assigning permissions to multiple users
- Viewing and editing user permissions
- Revoking permissions from users

The dialog uses a tabbed interface with two main sections:
1. "Asignación de Usuarios" - For bulk permission assignment
2. "Gestión de Permisos" - For viewing and managing individual user permissions

All database operations use parameterized queries and quoted identifiers to prevent SQL injection.
Only GRANT and REVOKE operations are performed; no data is modified.

Classes:
    validateDialog: Main dialog class for permission management interface

Author: Servinformacion
License: GNU General Public License v2.0 or later
"""
from .permisos import concederPermisos, obtenerUsuariosYPermisos, revocarPermisosUsuarios, obtenerPermisosDetallados, registrarLogGestion

import os
import psycopg2
import time
import logging
from datetime import datetime

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout, QLabel, QListWidgetItem
from PyQt5.QtCore import Qt

from qgis.core import QgsDataSourceUri, QgsVectorLayer, QgsProject
from qgis.utils import iface

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Validaciones Servinfomacion_dialog_base.ui'))
    
FORM_CLASS_WINDOW, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'credentials.ui'))

class validateDialog(QtWidgets.QDialog, FORM_CLASS, FORM_CLASS_WINDOW):
    """Main dialog class for PostgreSQL permission management.
    
    This class provides the user interface for managing PostgreSQL database permissions.
    It inherits from QDialog and loads UI elements from two .ui files:
    - Validaciones Servinfomacion_dialog_base.ui: Main dialog layout
    - credentials.ui: Credentials panel layout
    
    The dialog manages two main workflows:
    1. Bulk permission assignment to multiple users
    2. Individual user permission management and editing
    
    Attributes:
        usuario_actual (str): Currently selected user for permission management
        usuarios_permisos_dict (dict): Cache of users and their permissions
        permisos_usuario_actual (dict): Detailed permissions of the current user
    
    Security Notes:
        - All database identifiers (usernames, schemas, tables) are quoted to prevent SQL injection
        - Only GRANT and REVOKE operations are performed; no data is modified
        - Connections are validated before operations
        - All operations require admin credentials
    """
    
    def __init__(self, parent=None):
        """Initialize the validateDialog.
        
        Sets up the UI from the .ui files and connects button signals to their
        respective slot methods. Initializes instance variables for tracking
        the current user and their permissions.
        
        Args:
            parent (QWidget, optional): Parent widget. Defaults to None.
        """
        super(validateDialog, self).__init__(parent)
        self.setupUi(self)
        
        # Configurar logging de auditoría
        self._configurar_logging()
        
        self.PBasignacion.clicked.connect(self.asignarUsuarios)
        self.PBvalidarPermisos.clicked.connect(self.validarPermisos)
        self.PBactualizarPermisos.clicked.connect(self.actualizarPermisos)
        self.PBquitarTodosPermisos.clicked.connect(self.quitarTodosPermisos)
        self.PBvalidarConexion.clicked.connect(self.validarConexion)
        self.listUsuariosPermisos.itemSelectionChanged.connect(self.mostrarPermisosUsuario)
        
        self.usuario_actual = None
        self.usuarios_permisos_dict = {}
        self.permisos_usuario_actual = {}
        
        # Crear referencia al widget mostrarProcesoPermisos si existe
        if not hasattr(self, 'mostrarProcesoPermisos'):
            self.mostrarProcesoPermisos = None
    
    def _configurar_logging(self):
        """Configura el sistema de logging de auditoría.
        
        Crea un archivo de log para registrar todas las operaciones de permisos.
        El archivo se guarda en la carpeta del plugin con timestamp.
        """
        try:
            # Crear carpeta de logs si no existe
            log_dir = os.path.join(os.path.dirname(__file__), 'logs')
            if not os.path.exists(log_dir):
                os.makedirs(log_dir)
            
            # Configurar logging
            log_file = os.path.join(log_dir, f'permisos_audit_{datetime.now().strftime("%Y%m%d")}.log')
            
            logging.basicConfig(
                filename=log_file,
                level=logging.INFO,
                format='%(asctime)s - %(levelname)s - %(message)s',
                datefmt='%Y-%m-%d %H:%M:%S'
            )
            
            self.logger = logging.getLogger(__name__)
        except Exception as e:
            # Si hay error en logging, continuar sin él
            self.logger = None
        
    def _registrar_auditoria(self, accion, detalles, usuario_admin=""):
        """Registra una acción en el log de auditoría.
        
        Args:
            accion (str): Tipo de acción (GRANT, REVOKE, VALIDAR, etc.)
            detalles (str): Detalles de la acción
            usuario_admin (str): Usuario que realizó la acción
        """
        if self.logger:
            try:
                mensaje = f"[{usuario_admin}] {accion}: {detalles}"
                self.logger.info(mensaje)
            except:
                pass
    
    def _actualizar_resumen(self, texto):
        """Actualiza el resumen en ambas pestañas.
        
        Args:
            texto (str): Texto a mostrar en el resumen
        """
        # Actualizar en la pestaña de Asignación
        if hasattr(self, 'mostrarProceso'):
            self.mostrarProceso.setText(texto)
            # Scroll al final
            self.mostrarProceso.verticalScrollBar().setValue(
                self.mostrarProceso.verticalScrollBar().maximum()
            )
        
        # Actualizar en la pestaña de Gestión de Permisos si existe
        if hasattr(self, 'mostrarProcesoPermisos') and self.mostrarProcesoPermisos:
            self.mostrarProcesoPermisos.setText(texto)
            # Scroll al final
            self.mostrarProcesoPermisos.verticalScrollBar().setValue(
                self.mostrarProcesoPermisos.verticalScrollBar().maximum()
            )
    
    def _agregar_linea_resumen(self, linea):
        """Agrega una línea al resumen en tiempo real.
        
        Args:
            linea (str): Línea a agregar
        """
        # Obtener texto actual
        if hasattr(self, 'mostrarProceso'):
            texto_actual = self.mostrarProceso.toPlainText()
            nuevo_texto = texto_actual + "\n" + linea if texto_actual else linea
            self._actualizar_resumen(nuevo_texto)
    
    def _validar_usuario_existe(self, cursor, usuario):
        """Valida si un usuario existe en PostgreSQL.
        
        Args:
            cursor: Cursor de psycopg2
            usuario (str): Nombre del usuario a validar
        
        Returns:
            bool: True si el usuario existe, False en caso contrario
        """
        try:
            query = "SELECT 1 FROM pg_user WHERE usename = %s"
            cursor.execute(query, (usuario,))
            return cursor.fetchone() is not None
        except:
            return False
    
    def mensaje(self, status, mess):
        """Display a message in the QGIS message bar.
        
        Shows temporary notifications to the user about operation status.
        Error messages are displayed in red, success messages in green.
        
        Args:
            status (str): Message type - "Error" or "Ejecutado" (Success)
            mess (str): Message text to display
        
        Returns:
            None
        """
        if status == "Error":
            iface.messageBar().pushMessage(status, mess, level = 2, duration = 5)
        if status == "Ejecutado":
            iface.messageBar().pushMessage(status, mess, level = 3, duration = 5)
    
    def credenciales(self):
        """Retrieve database connection credentials from the UI.
        
        Extracts the database connection parameters from the credentials panel
        text fields. These credentials are used for all database operations.
        
        Returns:
            tuple: A tuple containing (database, host, username, password)
                - database (str): Database name
                - host (str): PostgreSQL server hostname or IP
                - username (str): PostgreSQL user for authentication
                - password (str): PostgreSQL user password
        
        Note:
            All fields must be filled before attempting database operations.
            Use validarConexion() to verify credentials are correct.
        """
        bd = self.LEbd.text()
        host = self.LEhost.text()
        usuario = self.LEusuario.text()
        contrasena = self.QPLEcontrasena.text()
        return bd, host, usuario, contrasena
    
    def validarConexion(self):
        """Validate the PostgreSQL database connection.
        
        Tests the connection to the PostgreSQL database using the provided credentials.
        Displays a detailed summary with connection information and PostgreSQL version
        on success, or error details and troubleshooting suggestions on failure.
        
        The validation process:
        1. Retrieves credentials from the UI
        2. Validates all required fields are filled
        3. Attempts to connect to the database
        4. Retrieves PostgreSQL version information
        5. Displays results in the process summary panel
        
        Returns:
            None
        
        Side Effects:
            - Updates mostrarProceso text widget with results
            - Displays message bar notification
            - Processes Qt events to update UI
        
        Raises:
            psycopg2.OperationalError: If connection fails (caught and displayed)
            Exception: Any other unexpected errors (caught and displayed)
        
        Note:
            This method should be called before attempting other database operations
            to ensure credentials are correct and the server is accessible.
        """
        import psycopg2
        
        bd, host, usuario, contrasena = self.credenciales()
        
        # Validar que los campos no estén vacíos
        if not all([bd, host, usuario, contrasena]):
            self.mostrarProceso.setText('❌ Error: Completa todos los campos de conexión')
            self.mensaje('Error', 'Completa todos los campos')
            return
        
        self.mostrarProceso.setText('🔄 Validando conexión...\n')
        QApplication.processEvents()
        
        try:
            conn = psycopg2.connect(
                host=host, 
                database=bd, 
                user=usuario, 
                password=contrasena, 
                port='5432'
            )
            
            cursor = conn.cursor()
            cursor.execute("SELECT version();")
            version = cursor.fetchone()[0]
            
            cursor.close()
            conn.close()
            
            # Mostrar resultado exitoso
            resumen = "✅ VALIDACIÓN DE CONEXIÓN EXITOSA\n"
            resumen += "=" * 60 + "\n\n"
            resumen += f"🔗 Host: {host}\n"
            resumen += f"📊 Base de datos: {bd}\n"
            resumen += f"👤 Usuario: {usuario}\n"
            resumen += f"🐘 Versión PostgreSQL: {version.split(',')[0]}\n\n"
            resumen += "=" * 60 + "\n"
            resumen += "✓ La conexión a la base de datos es correcta\n"
            resumen += "✓ Puedes proceder con las operaciones\n"
            
            self.mostrarProceso.setText(resumen)
            self.mensaje('Ejecutado', 'Conexión validada exitosamente')
            
        except psycopg2.OperationalError as e:
            resumen = "❌ ERROR DE CONEXIÓN\n"
            resumen += "=" * 60 + "\n\n"
            resumen += f"🔗 Host: {host}\n"
            resumen += f"📊 Base de datos: {bd}\n"
            resumen += f"👤 Usuario: {usuario}\n\n"
            resumen += "Posibles causas:\n"
            resumen += "• Credenciales incorrectas\n"
            resumen += "• Host o puerto incorrecto\n"
            resumen += "• Base de datos no existe\n"
            resumen += "• Servidor PostgreSQL no está disponible\n\n"
            resumen += f"Detalles del error:\n{str(e)}\n"
            
            self.mostrarProceso.setText(resumen)
            self.mensaje('Error', 'Error de conexión')
            
        except Exception as e:
            resumen = "❌ ERROR INESPERADO\n"
            resumen += "=" * 60 + "\n\n"
            resumen += f"Detalles del error:\n{str(e)}\n"
            
            self.mostrarProceso.setText(resumen)
            self.mensaje('Error', str(e))
    
    def run(self, query):
        """Execute a SQL query on the database.
        
        Connects to the database using stored credentials and executes the provided
        SQL query. This is a legacy method used for simple query execution.
        
        Args:
            query (str): SQL query string to execute
        
        Returns:
            None
        
        Side Effects:
            - Updates mostrarProceso text widget with status
            - Displays message bar notification
            - Commits changes to the database
            - Processes Qt events to update UI
        
        Raises:
            psycopg2.OperationalError: If connection credentials are invalid
            Exception: If query execution fails
        
        Note:
            This method is primarily used for testing and simple operations.
            For permission management, use the specialized methods like
            asignarPermisosAUsuarios() or aplicarPermisosUsuario() instead.
        """
        QApplication.processEvents()
        bd, host, usuario, contrasena = self.credenciales()
        try:
            conn = psycopg2.connect(host = host, database = bd, user = usuario, password = contrasena, port = '5432')
            cursor = conn.cursor()
            cursor.execute(query)
            conn.commit()
            self.mensaje('Ejecutado','Se ha realizado la validación')
            self.mostrarProceso.setText('Proceso Terminado - Se ha realizado la validación exitosamente...')
            
        except psycopg2.OperationalError:
            self.mensaje('Error','Los datos de conexión son erróneos')
            self.mostrarProceso.setText('Error Conexion - Los datos de conexión son erróneos...')
        
        except Exception as e:
            self.mensaje('Error','No se pudo ejecutar el Query')
            self.mostrarProceso.setText('Error query - No se pudo ejecutar el Query...')
    
    def asignarUsuarios(self):
        """Handle the bulk permission assignment workflow.
        
        Orchestrates the process of assigning permissions to multiple users:
        1. Retrieves comma-separated usernames from the input field
        2. Validates at least one user and one permission is selected
        3. Displays a confirmation dialog with operation details
        4. Calls asignarPermisosAUsuarios() to perform the assignment
        5. Displays a detailed summary of the operation
        
        The method validates:
        - At least one username is provided
        - At least one permission checkbox is selected
        - User confirms the operation via dialog
        
        Returns:
            None
        
        Side Effects:
            - Updates mostrarProceso text widget with results
            - Displays confirmation dialog
            - Displays message bar notification
            - Processes Qt events to update UI
        
        Raises:
            Exception: If permission assignment fails (caught and displayed)
        
        Note:
            Permissions are applied to ALL tables in the database.
            Users should be entered as comma-separated values (e.g., "user1, user2, user3").
        """
        from PyQt5.QtWidgets import QMessageBox, QDialog, QVBoxLayout, QLabel, QHBoxLayout, QPushButton
        from PyQt5.QtCore import Qt
        
        # Obtener usuarios
        usuarios_texto = self.TXEusuarios.toPlainText().strip()
        if not usuarios_texto:
            self.mensaje('Error', 'Ingresa al menos un usuario')
            return
        
        # Parsear usuarios
        usuarios = [u.strip() for u in usuarios_texto.split(',') if u.strip()]
        
        # Obtener permisos seleccionados
        permisos_seleccionados = []
        if self.checkAsignSELECT.isChecked():
            permisos_seleccionados.append('SELECT')
        if self.checkAsignINSERT.isChecked():
            permisos_seleccionados.append('INSERT')
        if self.checkAsignUPDATE.isChecked():
            permisos_seleccionados.append('UPDATE')
        if self.checkAsignDELETE.isChecked():
            permisos_seleccionados.append('DELETE')
        
        if not permisos_seleccionados:
            self.mensaje('Error', 'Selecciona al menos un permiso')
            return
        
        # Crear diálogo personalizado
        usuarios_str = ', '.join(usuarios)
        permisos_str = ', '.join(permisos_seleccionados)
        
        dialogo = QDialog(self)
        dialogo.setWindowTitle('Confirmar Asignación de Permisos')
        dialogo.setMinimumWidth(500)
        dialogo.setStyleSheet("""
            QDialog {
                background-color: #f5f5f5;
            }
            QLabel {
                color: #333;
            }
        """)
        
        layout = QVBoxLayout()
        
        # Título
        titulo = QLabel('✓ Confirmar Asignación de Permisos')
        titulo.setStyleSheet('font-weight: bold; font-size: 14px; color: #2196F3; margin-bottom: 15px;')
        layout.addWidget(titulo)
        
        # Contenido
        contenido = QLabel(
            f"<b>¿Deseas asignar los siguientes permisos?</b><br><br>"
            f"<b>Usuarios:</b> {usuarios_str}<br><br>"
            f"<b>Permisos:</b> {permisos_str}<br><br>"
            f"<i>Esta acción se aplicará a TODAS las tablas de la base de datos.</i>"
        )
        contenido.setStyleSheet('color: #555; line-height: 1.6;')
        layout.addWidget(contenido)
        
        layout.addSpacing(20)
        
        # Botones
        botones_layout = QHBoxLayout()
        botones_layout.addStretch()
        
        btn_si = QPushButton('✓ Sí, Asignar')
        btn_si.setMinimumWidth(120)
        btn_si.setMinimumHeight(40)
        btn_si.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
            QPushButton:pressed {
                background-color: #3d8b40;
            }
        """)
        
        btn_no = QPushButton('✗ Cancelar')
        btn_no.setMinimumWidth(120)
        btn_no.setMinimumHeight(40)
        btn_no.setStyleSheet("""
            QPushButton {
                background-color: #f44336;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #da190b;
            }
            QPushButton:pressed {
                background-color: #ba0000;
            }
        """)
        
        botones_layout.addWidget(btn_si)
        botones_layout.addWidget(btn_no)
        botones_layout.addStretch()
        
        layout.addLayout(botones_layout)
        dialogo.setLayout(layout)
        
        # Conectar botones
        btn_si.clicked.connect(dialogo.accept)
        btn_no.clicked.connect(dialogo.reject)
        
        # Mostrar diálogo
        if dialogo.exec_() != QDialog.Accepted:
            self.mostrarProceso.setText('Operación cancelada por el usuario.')
            return
        
        self.mostrarProceso.setText('Procesando asignación de permisos...\n')
        QApplication.processEvents()
        
        bd, host, usuario_admin, contrasena = self.credenciales()
        
        try:
            resumen = self.asignarPermisosAUsuarios(host, bd, usuario_admin, contrasena, usuarios, permisos_seleccionados)
            self.mostrarProceso.setText(resumen)
            self.mensaje('Ejecutado', 'Permisos asignados exitosamente')
            
        except Exception as e:
            self.mostrarProceso.setText(f'Error: {str(e)}')
            self.mensaje('Error', str(e))
    
    def asignarPermisosAUsuarios(self, host, bd, usuario_admin, contrasena, usuarios, permisos):
        """Assign permissions to multiple users on all database tables.
        
        Performs the actual GRANT operations to assign specified permissions to
        multiple users across all tables in the database. This method:
        1. Retrieves all tables from the database
        2. Validates each user exists before attempting GRANT
        3. For each user and permission combination, executes GRANT statements
        4. Generates a detailed summary of the operation
        5. Handles errors gracefully without stopping the process
        6. Logs all operations for audit trail
        
        Args:
            host (str): PostgreSQL server hostname or IP
            bd (str): Database name
            usuario_admin (str): Admin username for authentication
            contrasena (str): Admin password for authentication
            usuarios (list): List of usernames to grant permissions to
            permisos (list): List of permission types to grant (SELECT, INSERT, UPDATE, DELETE)
        
        Returns:
            str: Detailed summary of the operation including:
                - Number of tables found
                - Number of users processed
                - Permissions assigned per user and permission type
                - Total permissions assigned
                - Any errors encountered
        
        Raises:
            Exception: If database connection fails or critical error occurs
        
        Side Effects:
            - Executes GRANT statements on the database
            - Commits changes to the database
            - Logs all operations to audit trail
        
        Security Notes:
            - All identifiers (usernames, schemas, tables) are quoted to prevent SQL injection
            - Uses parameterized connections (psycopg2)
            - Validates users exist before GRANT
            - Only performs GRANT operations; no data is modified
        
        Example:
            >>> summary = dialog.asignarPermisosAUsuarios(
            ...     'localhost', 'mydb', 'admin', 'password',
            ...     ['user1', 'user2'], ['SELECT', 'INSERT']
            ... )
            >>> print(summary)
        """
        import psycopg2
        from .permisos import obtenerTablasBaseDatos
        
        resumen = "RESUMEN DE ASIGNACIÓN DE PERMISOS\n"
        resumen += "=" * 60 + "\n\n"
        
        try:
            # Obtener tablas
            tablas = obtenerTablasBaseDatos(host, bd, usuario_admin, contrasena)
            
            resumen += f"📊 Tablas encontradas: {len(tablas)}\n"
            resumen += f"👥 Usuarios a procesar: {len(usuarios)}\n"
            resumen += f"🔐 Permisos a asignar: {', '.join(permisos)}\n\n"
            
            self._actualizar_resumen(resumen)
            QApplication.processEvents()
            
            # Registrar inicio de operación
            self._registrar_auditoria(
                "ASIGNACIÓN_INICIO",
                f"Usuarios: {', '.join(usuarios)}, Permisos: {', '.join(permisos)}, Tablas: {len(tablas)}",
                usuario_admin
            )
            
            if len(tablas) == 0:
                resumen += "⚠️ No se encontraron tablas en la base de datos\n"
                self._actualizar_resumen(resumen)
                self._registrar_auditoria("ASIGNACIÓN_ERROR", "No se encontraron tablas", usuario_admin)
                return resumen
            
            with psycopg2.connect(
                host=host, 
                database=bd, 
                user=usuario_admin, 
                password=contrasena, 
                port='5432'
            ) as conn:
                with conn.cursor() as cursor:
                    total_permisos = 0
                    errores = 0
                    usuarios_validos = []
                    usuarios_invalidos = []
                    
                    # Validar usuarios antes de procesar
                    resumen += "🔍 Validando usuarios...\n"
                    self._actualizar_resumen(resumen)
                    QApplication.processEvents()
                    
                    for usuario in usuarios:
                        if self._validar_usuario_existe(cursor, usuario):
                            usuarios_validos.append(usuario)
                            resumen += f"   ✓ {usuario} - Válido\n"
                        else:
                            usuarios_invalidos.append(usuario)
                            resumen += f"   ✗ {usuario} - NO ENCONTRADO\n"
                            self._registrar_auditoria(
                                "VALIDACIÓN_ERROR",
                                f"Usuario no existe: {usuario}",
                                usuario_admin
                            )
                        self._actualizar_resumen(resumen)
                        QApplication.processEvents()
                    
                    if usuarios_invalidos:
                        resumen += f"\n⚠️ Usuarios no encontrados: {', '.join(usuarios_invalidos)}\n\n"
                    
                    if not usuarios_validos:
                        resumen += "❌ No hay usuarios válidos para procesar\n"
                        self._actualizar_resumen(resumen)
                        self._registrar_auditoria(
                            "ASIGNACIÓN_ERROR",
                            "Ningún usuario válido encontrado",
                            usuario_admin
                        )
                        return resumen
                    
                    resumen += f"\n🚀 Iniciando asignación de permisos...\n"
                    self._actualizar_resumen(resumen)
                    QApplication.processEvents()
                    
                    for usuario in usuarios_validos:
                        resumen += f"\n👤 Procesando usuario: {usuario}\n"
                        resumen += "-" * 60 + "\n"
                        self._actualizar_resumen(resumen)
                        QApplication.processEvents()
                        
                        usuario_permisos = 0
                        permisos_asignados_lista = []
                        
                        for permiso in permisos:
                            permisos_asignados_permiso = 0
                            
                            for esquema, tabla in tablas:
                                try:
                                    grant_query = f'GRANT {permiso} ON TABLE "{esquema}"."{tabla}" TO "{usuario}";'
                                    cursor.execute(grant_query)
                                    usuario_permisos += 1
                                    permisos_asignados_permiso += 1
                                    total_permisos += 1
                                    
                                    # Registrar en auditoría
                                    self._registrar_auditoria(
                                        "GRANT",
                                        f"Usuario: {usuario}, Permiso: {permiso}, Tabla: {esquema}.{tabla}",
                                        usuario_admin
                                    )
                                except psycopg2.Error as e:
                                    errores += 1
                                    # Solo mostrar errores críticos
                                    if "already" not in str(e).lower():
                                        resumen += f"   ⚠️ Error en {esquema}.{tabla} ({permiso}): {str(e)[:50]}\n"
                                        self._actualizar_resumen(resumen)
                                        QApplication.processEvents()
                                        self._registrar_auditoria(
                                            "GRANT_ERROR",
                                            f"Usuario: {usuario}, Tabla: {esquema}.{tabla}, Error: {str(e)}",
                                            usuario_admin
                                        )
                                except Exception as e:
                                    errores += 1
                            
                            if permisos_asignados_permiso > 0:
                                permisos_asignados_lista.append(permiso)
                                resumen += f"   ✓ {permiso}: {permisos_asignados_permiso} tablas\n"
                                self._actualizar_resumen(resumen)
                                QApplication.processEvents()
                        
                        resumen += f"   📈 Total para {usuario}: {usuario_permisos} permisos\n"
                        self._actualizar_resumen(resumen)
                        QApplication.processEvents()
                        
                        # Registrar en la base de datos 00_LogGestionUsuarios
                        try:
                            permisos_str = ','.join(permisos_asignados_lista)
                            registrarLogGestion(
                                host=host,
                                usuario_admin=usuario_admin,
                                contrasena=contrasena,
                                tipo_gestion='ASIGNACION PERMISOS',
                                bd_objetivo=bd,
                                usuario_gestionado=usuario,
                                permisos=permisos_str,
                                usuario_gestion=usuario_admin
                            )
                        except Exception as e:
                            resumen += f"   ⚠️ Error al registrar log: {str(e)[:50]}\n"
                            self._actualizar_resumen(resumen)
                            QApplication.processEvents()
                    
                    conn.commit()
            
            resumen += "\n" + "=" * 60 + "\n"
            resumen += f"✅ PROCESO COMPLETADO\n"
            resumen += f"   • Total de permisos asignados: {total_permisos}\n"
            resumen += f"   • Usuarios procesados: {len(usuarios_validos)}\n"
            resumen += f"   • Tablas procesadas: {len(tablas)}\n"
            resumen += f"   • Permisos aplicados: {', '.join(permisos)}\n"
            if errores > 0:
                resumen += f"   • Errores encontrados: {errores}\n"
            
            self._actualizar_resumen(resumen)
            QApplication.processEvents()
            
            # Registrar finalización
            self._registrar_auditoria(
                "ASIGNACIÓN_COMPLETADA",
                f"Permisos asignados: {total_permisos}, Errores: {errores}",
                usuario_admin
            )
            
            return resumen
            
        except Exception as e:
            resumen += f"\n❌ ERROR CRÍTICO: {str(e)}\n"
            self._actualizar_resumen(resumen)
            QApplication.processEvents()
            self._registrar_auditoria(
                "ASIGNACIÓN_ERROR_CRÍTICO",
                f"Error: {str(e)}",
                usuario_admin
            )
            raise Exception(f"Error al asignar permisos: {str(e)}")
    
    def validarPermisos(self):
        """Retrieve and display users with database permissions.
        
        Queries the database to find all users that have explicit permissions
        on tables. Populates the user list widget with checkboxes for each user
        found. This method:
        1. Calls obtenerUsuariosYPermisos() to get users with permissions
        2. Clears the previous user list
        3. Adds each user as a checked item in the list widget
        4. Caches user permissions for later use
        5. Displays the count of users found
        
        Returns:
            None
        
        Side Effects:
            - Updates listUsuariosPermisos widget with user list
            - Updates usuarios_permisos_dict cache
            - Updates mostrarProceso text widget with results
            - Displays message bar notification
            - Processes Qt events to update UI
        
        Raises:
            Exception: If database query fails (caught and displayed)
        
        Note:
            Only users with explicit permissions on tables are shown.
            Inherited permissions are not included.
            Call this method before mostrarPermisosUsuario() to populate the list.
        """
        self.mostrarProceso.setText('Obteniendo usuarios y permisos...')
        QApplication.processEvents()
        
        bd, host, usuario, contrasena = self.credenciales()
        
        try:
            usuarios_permisos = obtenerUsuariosYPermisos(host, bd, usuario, contrasena)
            
            # Limpiar lista anterior
            self.listUsuariosPermisos.clear()
            self.usuarios_permisos_dict = {}
            
            # Agregar usuarios a la lista con checkboxes
            for user, permisos in usuarios_permisos:
                item = QListWidgetItem(user)
                item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
                item.setCheckState(Qt.Checked)
                item.setData(Qt.UserRole, user)
                self.listUsuariosPermisos.addItem(item)
                self.usuarios_permisos_dict[user] = permisos
            
            self.mostrarProceso.setText(f'Se encontraron {len(usuarios_permisos)} usuarios con permisos.')
            self.mensaje('Ejecutado', f'Se encontraron {len(usuarios_permisos)} usuarios')
            
        except Exception as e:
            self.mostrarProceso.setText(f'Error: {str(e)}')
            self.mensaje('Error', str(e))
    
    def mostrarPermisosUsuario(self):
        """Display permissions for the selected user.
        
        When a user is selected from the list, this method:
        1. Retrieves the selected username
        2. Queries the database for detailed permissions
        3. Updates permission checkboxes based on user's permissions
        4. Populates the permissions table with schema/table/permission details
        5. Updates the group box title to show the current user
        
        The permissions table shows:
        - Schema name
        - Table name
        - SELECT permission (✓ if granted)
        - INSERT permission (✓ if granted)
        - UPDATE permission (✓ if granted)
        - DELETE permission (✓ if granted)
        
        Returns:
            None
        
        Side Effects:
            - Updates checkSELECT, checkINSERT, checkUPDATE, checkDELETE checkboxes
            - Updates tablasPermisosTable with permission details
            - Updates permisosGroupBox title
            - Updates usuario_actual instance variable
            - Updates permisos_usuario_actual cache
            - Displays message bar notification on error
        
        Raises:
            Exception: If database query fails (caught and displayed)
        
        Note:
            This method is called automatically when a user is selected.
            The checkboxes can be modified and then saved using actualizarPermisos().
        """
        from PyQt5.QtWidgets import QTableWidgetItem
        
        items_seleccionados = self.listUsuariosPermisos.selectedItems()
        
        if not items_seleccionados:
            self.permisosGroupBox.setTitle("Selecciona un usuario para ver/editar permisos")
            self.checkSELECT.setChecked(False)
            self.checkINSERT.setChecked(False)
            self.checkUPDATE.setChecked(False)
            self.checkDELETE.setChecked(False)
            self.tablasPermisosTable.setRowCount(0)
            return
        
        usuario = items_seleccionados[0].data(Qt.UserRole)
        self.usuario_actual = usuario
        
        bd, host, usuario_admin, contrasena = self.credenciales()
        
        try:
            # Obtener permisos detallados del usuario
            permisos_detallados = obtenerPermisosDetallados(host, bd, usuario_admin, contrasena, usuario)
            
            self.permisos_usuario_actual = permisos_detallados
            
            # Actualizar checkboxes
            self.checkSELECT.setChecked(permisos_detallados.get('SELECT', False))
            self.checkINSERT.setChecked(permisos_detallados.get('INSERT', False))
            self.checkUPDATE.setChecked(permisos_detallados.get('UPDATE', False))
            self.checkDELETE.setChecked(permisos_detallados.get('DELETE', False))
            
            # Llenar tabla con permisos por tabla
            tablas = permisos_detallados.get('tablas', [])
            self.tablasPermisosTable.setRowCount(len(tablas))
            
            for row, tabla_info in enumerate(tablas):
                # Validar que tabla_info tenga suficientes elementos
                if len(tabla_info) < 6:
                    continue
                    
                esquema = tabla_info[0] if tabla_info[0] else ""
                tabla = tabla_info[1] if tabla_info[1] else ""
                tiene_select = tabla_info[2] if tabla_info[2] is not None else False
                tiene_insert = tabla_info[3] if tabla_info[3] is not None else False
                tiene_update = tabla_info[4] if tabla_info[4] is not None else False
                tiene_delete = tabla_info[5] if tabla_info[5] is not None else False
                
                # Esquema
                item_esquema = QTableWidgetItem(str(esquema))
                item_esquema.setFlags(item_esquema.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 0, item_esquema)
                
                # Tabla
                item_tabla = QTableWidgetItem(str(tabla))
                item_tabla.setFlags(item_tabla.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 1, item_tabla)
                
                # SELECT
                item_select = QTableWidgetItem("✓" if tiene_select else "")
                item_select.setFlags(item_select.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 2, item_select)
                
                # INSERT
                item_insert = QTableWidgetItem("✓" if tiene_insert else "")
                item_insert.setFlags(item_insert.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 3, item_insert)
                
                # UPDATE
                item_update = QTableWidgetItem("✓" if tiene_update else "")
                item_update.setFlags(item_update.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 4, item_update)
                
                # DELETE
                item_delete = QTableWidgetItem("✓" if tiene_delete else "")
                item_delete.setFlags(item_delete.flags() & ~Qt.ItemIsEditable)
                self.tablasPermisosTable.setItem(row, 5, item_delete)
            
            self.permisosGroupBox.setTitle(f"Permisos para: {usuario}")
            
        except Exception as e:
            self.mensaje('Error', f'Error al obtener permisos: {str(e)}')
    
    def actualizarPermisos(self):
        """Update permissions for the selected user based on checkbox state.
        
        Orchestrates the permission update workflow:
        1. Validates a user is selected
        2. Collects the state of all permission checkboxes
        3. Displays a confirmation dialog with operation details
        4. Calls aplicarPermisosUsuario() to apply changes
        5. Revokes permissions that are unchecked
        6. Grants permissions that are checked
        7. Refreshes the user list to show updated permissions
        
        The method:
        - Revokes ALL permissions first
        - Then grants only the selected permissions
        - Applies changes to all tables for the user
        
        Returns:
            None
        
        Side Effects:
            - Updates mostrarProceso text widget with results
            - Displays confirmation dialog
            - Displays message bar notification
            - Calls validarPermisos() to refresh the user list
            - Processes Qt events to update UI
        
        Raises:
            Exception: If permission update fails (caught and displayed)
        
        Note:
            Unchecked permissions will be revoked from the user.
            This method requires a user to be selected first.
        """
        from PyQt5.QtWidgets import QDialog, QVBoxLayout, QLabel, QHBoxLayout, QPushButton
        
        if not self.usuario_actual:
            self.mensaje('Error', 'Selecciona un usuario primero')
            return
        
        # Obtener permisos seleccionados
        permisos_activos = []
        if self.checkSELECT.isChecked():
            permisos_activos.append('SELECT')
        if self.checkINSERT.isChecked():
            permisos_activos.append('INSERT')
        if self.checkUPDATE.isChecked():
            permisos_activos.append('UPDATE')
        if self.checkDELETE.isChecked():
            permisos_activos.append('DELETE')
        
        # Crear diálogo personalizado
        permisos_str = ', '.join(permisos_activos) if permisos_activos else 'NINGUNO'
        
        dialogo = QDialog(self)
        dialogo.setWindowTitle('Confirmar Actualización de Permisos')
        dialogo.setMinimumWidth(500)
        dialogo.setStyleSheet("""
            QDialog {
                background-color: #f5f5f5;
            }
            QLabel {
                color: #333;
            }
        """)
        
        layout = QVBoxLayout()
        
        # Título
        titulo = QLabel('💾 Confirmar Actualización de Permisos')
        titulo.setStyleSheet('font-weight: bold; font-size: 14px; color: #FF9800; margin-bottom: 15px;')
        layout.addWidget(titulo)
        
        # Contenido
        contenido = QLabel(
            f"<b>¿Deseas actualizar los permisos del usuario?</b><br><br>"
            f"<b>Usuario:</b> {self.usuario_actual}<br><br>"
            f"<b>Nuevos Permisos:</b> {permisos_str}<br><br>"
            f"<i>Los permisos no seleccionados serán revocados.</i>"
        )
        contenido.setStyleSheet('color: #555; line-height: 1.6;')
        layout.addWidget(contenido)
        
        layout.addSpacing(20)
        
        # Botones
        botones_layout = QHBoxLayout()
        botones_layout.addStretch()
        
        btn_si = QPushButton('✓ Sí, Actualizar')
        btn_si.setMinimumWidth(120)
        btn_si.setMinimumHeight(40)
        btn_si.setStyleSheet("""
            QPushButton {
                background-color: #FF9800;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #e68900;
            }
            QPushButton:pressed {
                background-color: #cc7700;
            }
        """)
        
        btn_no = QPushButton('✗ Cancelar')
        btn_no.setMinimumWidth(120)
        btn_no.setMinimumHeight(40)
        btn_no.setStyleSheet("""
            QPushButton {
                background-color: #f44336;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #da190b;
            }
            QPushButton:pressed {
                background-color: #ba0000;
            }
        """)
        
        botones_layout.addWidget(btn_si)
        botones_layout.addWidget(btn_no)
        botones_layout.addStretch()
        
        layout.addLayout(botones_layout)
        dialogo.setLayout(layout)
        
        # Conectar botones
        btn_si.clicked.connect(dialogo.accept)
        btn_no.clicked.connect(dialogo.reject)
        
        # Mostrar diálogo
        if dialogo.exec_() != QDialog.Accepted:
            self.mensaje('Ejecutado', 'Operación cancelada')
            return
        
        self.mostrarProceso.setText('Actualizando permisos...')
        QApplication.processEvents()
        
        bd, host, usuario_admin, contrasena = self.credenciales()
        
        try:
            # Obtener todas las tablas del usuario
            tablas = self.permisos_usuario_actual.get('tablas', [])
            
            if not tablas:
                self.mensaje('Error', 'No hay tablas para actualizar')
                return
            
            # Aplicar permisos
            self.aplicarPermisosUsuario(host, bd, usuario_admin, contrasena, self.usuario_actual, permisos_activos, tablas)
            
            self.mostrarProceso.setText(f'Permisos actualizados exitosamente para {self.usuario_actual}.')
            self.mensaje('Ejecutado', f'Permisos actualizados para {self.usuario_actual}')
            
            # Actualizar lista
            self.validarPermisos()
            
        except Exception as e:
            self.mostrarProceso.setText(f'Error: {str(e)}')
            self.mensaje('Error', str(e))
    
    def aplicarPermisosUsuario(self, host, bd, usuario_admin, contrasena, usuario_objetivo, permisos_activos, tablas):
        """Apply selected permissions to a user on all specified tables.
        
        Performs the actual GRANT and REVOKE operations:
        1. Revokes ALL permissions on all tables first
        2. Then grants only the selected permissions
        3. Commits all changes to the database
        4. Logs all operations for audit trail
        
        This two-step approach ensures the user has exactly the permissions
        specified, with no extra permissions remaining.
        
        Args:
            host (str): PostgreSQL server hostname or IP
            bd (str): Database name
            usuario_admin (str): Admin username for authentication
            contrasena (str): Admin password for authentication
            usuario_objetivo (str): Username to apply permissions to
            permisos_activos (list): List of permissions to grant (SELECT, INSERT, UPDATE, DELETE)
            tablas (list): List of tuples (schema, table, ...) to apply permissions to
        
        Returns:
            None
        
        Raises:
            Exception: If database operations fail
        
        Side Effects:
            - Executes REVOKE ALL statements on all tables
            - Executes GRANT statements for selected permissions
            - Commits changes to the database
            - Logs all operations to audit trail
        
        Security Notes:
            - All identifiers are quoted to prevent SQL injection
            - Uses parameterized connections (psycopg2)
            - Only performs GRANT/REVOKE operations; no data is modified
        
        Example:
            >>> dialog.aplicarPermisosUsuario(
            ...     'localhost', 'mydb', 'admin', 'password',
            ...     'user1', ['SELECT', 'INSERT'],
            ...     [('public', 'table1'), ('public', 'table2')]
            ... )
        """
        import psycopg2
        
        try:
            with psycopg2.connect(
                host=host, 
                database=bd, 
                user=usuario_admin, 
                password=contrasena, 
                port='5432'
            ) as conn:
                with conn.cursor() as cursor:
                    # Registrar inicio de operación
                    self._registrar_auditoria(
                        "ACTUALIZACIÓN_INICIO",
                        f"Usuario: {usuario_objetivo}, Permisos: {', '.join(permisos_activos)}",
                        usuario_admin
                    )
                    
                    permisos_quitados = []
                    permisos_nuevos = []
                    
                    # Primero obtener permisos actuales
                    from .permisos import obtenerPermisosDetallados
                    permisos_actuales = obtenerPermisosDetallados(host, bd, usuario_admin, contrasena, usuario_objetivo)
                    permisos_actuales_set = set()
                    if permisos_actuales['SELECT']:
                        permisos_actuales_set.add('SELECT')
                    if permisos_actuales['INSERT']:
                        permisos_actuales_set.add('INSERT')
                    if permisos_actuales['UPDATE']:
                        permisos_actuales_set.add('UPDATE')
                    if permisos_actuales['DELETE']:
                        permisos_actuales_set.add('DELETE')
                    
                    # Calcular permisos nuevos y quitados
                    permisos_activos_set = set(permisos_activos)
                    permisos_nuevos = list(permisos_activos_set - permisos_actuales_set)
                    permisos_quitados = list(permisos_actuales_set - permisos_activos_set)
                    
                    # Primero revocar todos los permisos
                    for esquema, tabla, _, _, _, _ in tablas:
                        try:
                            cursor.execute(f'REVOKE ALL ON TABLE "{esquema}"."{tabla}" FROM "{usuario_objetivo}";')
                            self._registrar_auditoria(
                                "REVOKE_ALL",
                                f"Usuario: {usuario_objetivo}, Tabla: {esquema}.{tabla}",
                                usuario_admin
                            )
                        except psycopg2.Error:
                            pass
                    
                    # Luego otorgar solo los permisos seleccionados
                    for permiso in permisos_activos:
                        for esquema, tabla, _, _, _, _ in tablas:
                            try:
                                cursor.execute(f'GRANT {permiso} ON TABLE "{esquema}"."{tabla}" TO "{usuario_objetivo}";')
                                self._registrar_auditoria(
                                    "GRANT",
                                    f"Usuario: {usuario_objetivo}, Permiso: {permiso}, Tabla: {esquema}.{tabla}",
                                    usuario_admin
                                )
                            except psycopg2.Error:
                                pass
                    
                    conn.commit()
                    
                    # Registrar finalización
                    self._registrar_auditoria(
                        "ACTUALIZACIÓN_COMPLETADA",
                        f"Usuario: {usuario_objetivo}, Permisos: {', '.join(permisos_activos)}",
                        usuario_admin
                    )
                    
                    # Registrar en la base de datos 00_LogGestionUsuarios
                    try:
                        permisos_log = ""
                        if permisos_nuevos:
                            permisos_log += f"Nuevo({','.join(permisos_nuevos)})"
                        if permisos_quitados:
                            if permisos_log:
                                permisos_log += " - "
                            permisos_log += f"Quitados({','.join(permisos_quitados)})"
                        
                        if permisos_log:
                            registrarLogGestion(
                                host=host,
                                usuario_admin=usuario_admin,
                                contrasena=contrasena,
                                tipo_gestion='ACTUALIZACION PERMISOS',
                                bd_objetivo=bd,
                                usuario_gestionado=usuario_objetivo,
                                permisos=permisos_log,
                                usuario_gestion=usuario_admin
                            )
                    except Exception as e:
                        self._registrar_auditoria(
                            "LOG_ERROR",
                            f"Error al registrar log: {str(e)}",
                            usuario_admin
                        )
            
        except Exception as e:
            self._registrar_auditoria(
                "ACTUALIZACIÓN_ERROR",
                f"Usuario: {usuario_objetivo}, Error: {str(e)}",
                usuario_admin
            )
            raise Exception(f"Error al aplicar permisos: {str(e)}")
    
    def quitarTodosPermisos(self):
        """Revoke all permissions from the selected user.
        
        Orchestrates the complete permission revocation workflow:
        1. Validates a user is selected
        2. Displays a warning confirmation dialog
        3. Calls revocarTodosPermisosUsuario() to revoke all permissions
        4. Refreshes the user list to show updated permissions
        
        This is a destructive operation that removes ALL permissions from the user
        on all tables and schemas. A confirmation dialog is shown to prevent
        accidental execution.
        
        Returns:
            None
        
        Side Effects:
            - Updates mostrarProceso text widget with results
            - Displays warning confirmation dialog
            - Displays message bar notification
            - Calls validarPermisos() to refresh the user list
            - Processes Qt events to update UI
        
        Raises:
            Exception: If permission revocation fails (caught and displayed)
        
        Note:
            This method requires a user to be selected first.
            The operation cannot be undone - the user will have no permissions.
            A confirmation dialog is always shown before proceeding.
        """
        from PyQt5.QtWidgets import QDialog, QVBoxLayout, QLabel, QHBoxLayout, QPushButton
        
        if not self.usuario_actual:
            self.mensaje('Error', 'Selecciona un usuario primero')
            return
        
        # Crear diálogo personalizado
        dialogo = QDialog(self)
        dialogo.setWindowTitle('Confirmar Eliminación de Permisos')
        dialogo.setMinimumWidth(500)
        dialogo.setStyleSheet("""
            QDialog {
                background-color: #f5f5f5;
            }
            QLabel {
                color: #333;
            }
        """)
        
        layout = QVBoxLayout()
        
        # Título
        titulo = QLabel('🚫 Confirmar Eliminación de Permisos')
        titulo.setStyleSheet('font-weight: bold; font-size: 14px; color: #f44336; margin-bottom: 15px;')
        layout.addWidget(titulo)
        
        # Contenido
        contenido = QLabel(
            f"<b>⚠️ ADVERTENCIA: Esta acción no se puede deshacer</b><br><br>"
            f"¿Estás seguro de que deseas quitar <b>TODOS</b> los permisos al usuario?<br><br>"
            f"<b>Usuario:</b> {self.usuario_actual}<br><br>"
            f"<i>Se quitarán todos los permisos en todas las tablas y esquemas.</i>"
        )
        contenido.setStyleSheet('color: #555; line-height: 1.6;')
        layout.addWidget(contenido)
        
        layout.addSpacing(20)
        
        # Botones
        botones_layout = QHBoxLayout()
        botones_layout.addStretch()
        
        btn_si = QPushButton('🚫 Sí, Quitar Todos')
        btn_si.setMinimumWidth(140)
        btn_si.setMinimumHeight(40)
        btn_si.setStyleSheet("""
            QPushButton {
                background-color: #f44336;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #da190b;
            }
            QPushButton:pressed {
                background-color: #ba0000;
            }
        """)
        
        btn_no = QPushButton('✗ Cancelar')
        btn_no.setMinimumWidth(120)
        btn_no.setMinimumHeight(40)
        btn_no.setStyleSheet("""
            QPushButton {
                background-color: #2196F3;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                font-size: 11px;
            }
            QPushButton:hover {
                background-color: #0b7dda;
            }
            QPushButton:pressed {
                background-color: #0056b3;
            }
        """)
        
        botones_layout.addWidget(btn_si)
        botones_layout.addWidget(btn_no)
        botones_layout.addStretch()
        
        layout.addLayout(botones_layout)
        dialogo.setLayout(layout)
        
        # Conectar botones
        btn_si.clicked.connect(dialogo.accept)
        btn_no.clicked.connect(dialogo.reject)
        
        # Mostrar diálogo
        if dialogo.exec_() != QDialog.Accepted:
            self.mensaje('Ejecutado', 'Operación cancelada')
            return
        
        self.mostrarProceso.setText('Quitando todos los permisos...')
        QApplication.processEvents()
        
        bd, host, usuario_admin, contrasena = self.credenciales()
        
        try:
            # Obtener todas las tablas del usuario
            tablas = self.permisos_usuario_actual.get('tablas', [])
            
            if not tablas:
                self.mensaje('Error', 'No hay tablas para actualizar')
                return
            
            # Revocar todos los permisos
            self.revocarTodosPermisosUsuario(host, bd, usuario_admin, contrasena, self.usuario_actual, tablas)
            
            self.mostrarProceso.setText(f'Todos los permisos han sido quitados a {self.usuario_actual}.')
            self.mensaje('Ejecutado', f'Permisos quitados para {self.usuario_actual}')
            
            # Actualizar lista
            self.validarPermisos()
            
        except Exception as e:
            self.mostrarProceso.setText(f'Error: {str(e)}')
            self.mensaje('Error', str(e))
    
    def revocarTodosPermisosUsuario(self, host, bd, usuario_admin, contrasena, usuario_objetivo, tablas):
        """Revoke all permissions from a user on all tables and schemas.
        
        Performs the actual REVOKE operations:
        1. Revokes ALL permissions on all specified tables
        2. Revokes CONNECT permission on the database
        3. Commits all changes to the database
        4. Logs all operations for audit trail
        
        This method completely removes all permissions from the user, leaving them
        with no access to any tables or the database itself.
        
        Args:
            host (str): PostgreSQL server hostname or IP
            bd (str): Database name
            usuario_admin (str): Admin username for authentication
            contrasena (str): Admin password for authentication
            usuario_objetivo (str): Username to revoke permissions from
            tablas (list): List of tuples (schema, table, ...) to revoke permissions from
        
        Returns:
            None
        
        Raises:
            Exception: If database operations fail
        
        Side Effects:
            - Executes REVOKE ALL statements on all tables
            - Executes REVOKE CONNECT statement on the database
            - Commits changes to the database
            - Logs all operations to audit trail
        
        Security Notes:
            - All identifiers are quoted to prevent SQL injection
            - Uses parameterized connections (psycopg2)
            - Only performs REVOKE operations; no data is modified
            - Errors in individual REVOKE statements are silently ignored
              to ensure all revocations are attempted
        
        Example:
            >>> dialog.revocarTodosPermisosUsuario(
            ...     'localhost', 'mydb', 'admin', 'password',
            ...     'user1', [('public', 'table1'), ('public', 'table2')]
            ... )
        """
        import psycopg2
        
        try:
            with psycopg2.connect(
                host=host, 
                database=bd, 
                user=usuario_admin, 
                password=contrasena, 
                port='5432'
            ) as conn:
                with conn.cursor() as cursor:
                    # Registrar inicio de operación
                    self._registrar_auditoria(
                        "REVOCACIÓN_TOTAL_INICIO",
                        f"Usuario: {usuario_objetivo}",
                        usuario_admin
                    )
                    
                    permisos_quitados = []
                    
                    # Obtener permisos actuales antes de revocar
                    from .permisos import obtenerPermisosDetallados
                    permisos_actuales = obtenerPermisosDetallados(host, bd, usuario_admin, contrasena, usuario_objetivo)
                    if permisos_actuales['SELECT']:
                        permisos_quitados.append('SELECT')
                    if permisos_actuales['INSERT']:
                        permisos_quitados.append('INSERT')
                    if permisos_actuales['UPDATE']:
                        permisos_quitados.append('UPDATE')
                    if permisos_actuales['DELETE']:
                        permisos_quitados.append('DELETE')
                    
                    # Revocar permisos en todas las tablas
                    for esquema, tabla, _, _, _, _ in tablas:
                        try:
                            cursor.execute(f'REVOKE ALL ON TABLE "{esquema}"."{tabla}" FROM "{usuario_objetivo}";')
                            self._registrar_auditoria(
                                "REVOKE_ALL",
                                f"Usuario: {usuario_objetivo}, Tabla: {esquema}.{tabla}",
                                usuario_admin
                            )
                        except psycopg2.Error:
                            pass
                    
                    # Revocar conexión a la BD
                    try:
                        cursor.execute(f'REVOKE CONNECT ON DATABASE "{bd}" FROM "{usuario_objetivo}";')
                        self._registrar_auditoria(
                            "REVOKE_CONNECT",
                            f"Usuario: {usuario_objetivo}, Base de datos: {bd}",
                            usuario_admin
                        )
                    except psycopg2.Error:
                        pass
                    
                    conn.commit()
                    
                    # Registrar finalización
                    self._registrar_auditoria(
                        "REVOCACIÓN_TOTAL_COMPLETADA",
                        f"Usuario: {usuario_objetivo}",
                        usuario_admin
                    )
                    
                    # Registrar en la base de datos 00_LogGestionUsuarios
                    try:
                        permisos_str = ','.join(permisos_quitados) if permisos_quitados else 'TODOS'
                        registrarLogGestion(
                            host=host,
                            usuario_admin=usuario_admin,
                            contrasena=contrasena,
                            tipo_gestion='QUITAR PERMISOS',
                            bd_objetivo=bd,
                            usuario_gestionado=usuario_objetivo,
                            permisos=permisos_str,
                            usuario_gestion=usuario_admin
                        )
                    except Exception as e:
                        self._registrar_auditoria(
                            "LOG_ERROR",
                            f"Error al registrar log: {str(e)}",
                            usuario_admin
                        )
            
        except Exception as e:
            self._registrar_auditoria(
                "REVOCACIÓN_ERROR",
                f"Usuario: {usuario_objetivo}, Error: {str(e)}",
                usuario_admin
            )
            raise Exception(f"Error al revocar permisos: {str(e)}")
